# This file was generated by GoReleaser. DO NOT EDIT.
cask "openmcf" do
  version "0.3.76-cli.20260604.0"

  on_macos do
    on_intel do
      sha256 "63199752a270677c5cf8b676f9005ce901e53db5ce1783db3c3b022af33722df"
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1354486f701b040a130387e76ca50979b2601f932d9aff850306daa662740ed3"
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "46ee631c99f77acbc0e6a5ff424b59d393bed28660f14c69ec44777791091543"
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c69b673f73893819eaebc2fc2b269edd011def882d48b7f951c9ba3cf7d8cf00"
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "openmcf"
  desc "OpenMCF CLI - Infrastructure as Code made simple"
  homepage "https://github.com/plantonhq/openmcf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openmcf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openmcf"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Installation Complete!

    OpenMCF CLI helps you manage infrastructure deployments.

    Quick Start

    1. Check the version:
       openmcf version

    2. Get help:
       openmcf --help

    Documentation: https://github.com/plantonhq/openmcf
  EOS
end
