# This file was generated by GoReleaser. DO NOT EDIT.
cask "openmcf" do
  version "0.3.63-cli.20260515.0"

  on_macos do
    on_intel do
      sha256 "3312b7f8f0da57e525cf2109e67713b0dd5099aa3588c995543bc2aeec14e75c"
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1218bf803ceb1dc2125040a284f97561d04ccf299d9df6bf44f37bd37e54a9b1"
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "058bc96bae476888bff9f029d58c089ed130dfd629ca69e31bf69971a26e009c"
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "325829dd13919da03dd01b056b43e4bf468c708089be2df27dd51cbb331224ec"
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "openmcf"
  desc "OpenMCF CLI - Infrastructure as Code made simple"
  homepage "https://github.com/plantonhq/openmcf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openmcf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openmcf"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Installation Complete!

    OpenMCF CLI helps you manage infrastructure deployments.

    Quick Start

    1. Check the version:
       openmcf version

    2. Get help:
       openmcf --help

    Documentation: https://github.com/plantonhq/openmcf
  EOS
end
