# This file was generated by GoReleaser. DO NOT EDIT.
cask "openmcf" do
  version "0.3.72"

  on_macos do
    on_intel do
      sha256 "08474c43b46c6e184ca45e98af4525fc0d6024f0aa64f43e8c5856d2db6f9818"
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "31f6e9a2eefeea55b20bf4aab37ef5869aa26897893cb3662c21efebca3ba328"
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "38b5cb2421c04bc6344b703a290611d81968879d0490eccc3ab555a9c0f7019d"
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9b46d52f820dec94f95edbbaa260329013924a11cec801f7726150787766c36c"
      url "https://github.com/plantonhq/openmcf/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "openmcf"
  desc "OpenMCF CLI - Infrastructure as Code made simple"
  homepage "https://github.com/plantonhq/openmcf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openmcf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openmcf"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Installation Complete!

    OpenMCF CLI helps you manage infrastructure deployments.

    Quick Start

    1. Check the version:
       openmcf version

    2. Get help:
       openmcf --help

    Documentation: https://github.com/plantonhq/openmcf
  EOS
end
