# This file was generated by GoReleaser. DO NOT EDIT.
cask "planton" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "b98cff4b058edf98f943a36ac5148937b10d632b998715657c771f73cbacdca9"
      url "https://github.com/plantonhq/planton/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0018c35245d5b693918aee0526d49121d211eaa44ac5806232035df92b0e85fb"
      url "https://github.com/plantonhq/planton/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3889bec6e8a019964555826b9a209ed05f903e7fb58ba2ed0ba26047b94f9e35"
      url "https://github.com/plantonhq/planton/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3006fffa63b2aaad7db70e1239fe9e5ac346d1b5154ec9849ab3d45894fad165"
      url "https://github.com/plantonhq/planton/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "planton"
  desc "Planton CLI - Infrastructure as Code made simple"
  homepage "https://github.com/plantonhq/planton"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "planton"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/planton"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Installation Complete!

    Planton CLI helps you manage infrastructure deployments.

    Quick Start

    1. Check the version:
       planton version

    2. Get help:
       planton --help

    Documentation: https://github.com/plantonhq/planton
  EOS
end
