# This file was generated by GoReleaser. DO NOT EDIT.
cask "planton" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "e806cb7eb63b9427f827c09302357c4276025aec5cca172e8aefebcbac0a5bd5"
      url "https://github.com/plantonhq/planton/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e02cb0809ee5a4634de59537fed3d8894d8255574220bf6e92cd79f3e8614725"
      url "https://github.com/plantonhq/planton/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ecc998a45cdb16bc2b99ddbc31a3086c38691a2b1fe9896694d72d5590a05565"
      url "https://github.com/plantonhq/planton/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7146b0c724ceb12b3e6d7a7b7b5c18a36e4286cbe9b109b6752acb70512c02e6"
      url "https://github.com/plantonhq/planton/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "planton"
  desc "Planton CLI - Infrastructure as Code made simple"
  homepage "https://github.com/plantonhq/planton"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "planton"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/planton"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Installation Complete!

    Planton CLI helps you manage infrastructure deployments.

    Quick Start

    1. Check the version:
       planton version

    2. Get help:
       planton --help

    Documentation: https://github.com/plantonhq/planton
  EOS
end
