# This file was generated by GoReleaser. DO NOT EDIT.
cask "planton" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "b67b126bc7ffc6fe38c95e776ad4c2927d95174ef38ba44ab8f19835daf9162d"
      url "https://github.com/plantonhq/planton/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0eacecf09b647ce9b595176aac1133c0841920a7f3d511011c162608ed5f7d37"
      url "https://github.com/plantonhq/planton/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9d2293619c901ba2552525a1308b6118a29c5a37dd9a672df4fd061eb048045f"
      url "https://github.com/plantonhq/planton/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b9e7c2c88745c1525f24b8163b3164fdf710263f95ed4382edd1acf725b17355"
      url "https://github.com/plantonhq/planton/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "planton"
  desc "Planton CLI - Infrastructure as Code made simple"
  homepage "https://github.com/plantonhq/planton"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "planton"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/planton"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Installation Complete!

    Planton CLI helps you manage infrastructure deployments.

    Quick Start

    1. Check the version:
       planton version

    2. Get help:
       planton --help

    Documentation: https://github.com/plantonhq/planton
  EOS
end
